extends: default

rules:
  line-length:
    max: 100
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  key-ordering: {}
  indentation:
    spaces: 2
    check-multi-line-strings: false
  truthy: false
